// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBghaK7OqwZYxLAz_sSPvDAKsHLf6fJQig",
    appId: "1:1081946430682:web:9ce00eca55680fde6f59e3",
    messagingSenderId: "1081946430682",
    projectId: "nail-technician-app",
    storageBucket: "nail-technician-app.appspot.com",
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBghaK7OqwZYxLAz_sSPvDAKsHLf6fJQig",
      authDomain: "nail-technician-app.firebaseapp.com",
      projectId: "nail-technician-app",
      storageBucket: "nail-technician-app.appspot.com",
      messagingSenderId: "1081946430682",
      appId: "1:1081946430682:web:9ce00eca55680fde6f59e3",
      measurementId: "G-TT9WRF7NYV"
  );
}
